//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevLifeTG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TravieIOEntities1 : DbContext
    {
        public TravieIOEntities1()
            : base("name=TravieIOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HighScore> HighScores { get; set; }
    
        public virtual ObjectResult<uspGetHighScores_Result> uspGetHighScores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetHighScores_Result>("uspGetHighScores");
        }
    
        public virtual ObjectResult<HighScore> GetTopScore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HighScore>("GetTopScore");
        }
    
        public virtual ObjectResult<HighScore> GetTopScore(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HighScore>("GetTopScore", mergeOption);
        }
    }
}
